// Procédures internes de l'agence (« Process »). Contenu en « markdown léger » :
// "## " = étape / sous-titre, "- " = puce, "> " = point de vigilance, **gras**.
// Ces textes sont des valeurs PAR DÉFAUT : le manager peut les personnaliser
// (stockage serveur, voir serverProcess). À adapter à l'organisation réelle.

export interface ProcessDef {
  id: string;
  titre: string;
  icone: string;
  resume: string;
  contenu: string[];
}

export const PROCESS_DEFAUT: ProcessDef[] = [
  {
    id: "mandat",
    titre: "Rentrée du mandat de vente",
    icone: "📝",
    resume: "De la signature du mandat à la mise en commercialisation.",
    contenu: [
      "Objectif : sécuriser le dossier et lancer une commercialisation efficace dès la signature du mandat.",
      "## Étape 1 — Signer un mandat conforme",
      "- Vérifier l'identité du/des **propriétaire(s)** et leur droit à vendre (titre de propriété, indivision, SCI).",
      "- Mandat **écrit**, daté, en autant d'exemplaires que de parties, avec **numéro du registre des mandats**.",
      "- Mentions obligatoires : prix, honoraires (qui paie), durée, conditions, **barème affiché** (loi ALUR / Hoguet).",
      "- Privilégier le **mandat exclusif** : plan d'action renforcé et engagement réciproque.",
      "## Étape 2 — Réunir les pièces",
      "- **Pièce d'identité** du/des vendeur(s), **titre de propriété**, dernier avis de taxe foncière.",
      "- **Diagnostics (DDT)** : DPE obligatoire **dès l'annonce**, + amiante, plomb, électricité, gaz, ERP, mesurage Carrez si copropriété.",
      "- Copropriété : règlement, PV d'AG, carnet d'entretien, pré-état daté / montant des charges.",
      "## Étape 3 — Conformité LCB-FT (Tracfin)",
      "- Renseigner la **fiche de vigilance** (identité, origine des fonds, bénéficiaire effectif) : KYC obligatoire.",
      "> En cas de doute sérieux, ne pas poursuivre sans valider la vigilance : déclaration de soupçon possible.",
      "## Étape 4 — Créer et classer le dossier",
      "- Créer le **dossier vendeur** dans le CRM (nom du vendeur, bien, négociateur).",
      "- Y déposer toutes les pièces et diagnostics ; vérifier que le dossier est **complet**.",
      "## Étape 5 — Préparer la commercialisation",
      "- **Prix** validé par l'avis de valeur (DVF) ; annexer l'avis de valeur au dossier.",
      "- **Photos professionnelles** + conseils **home-staging** ; rédiger un **texte d'annonce** vendeur (bénéfices, pas que caractéristiques).",
      "- Préparer le **panneau** « À vendre » (accord du vendeur) et la vitrine.",
      "## Étape 6 — Diffuser",
      "- Mise en ligne **portails** (SeLoger, Leboncoin, Bien'ici…), **site agence**, **vitrine**.",
      "- Poster dans le **groupe WhatsApp** de l'équipe (voir process dédié) pour matching interne.",
      "- **Croiser avec le portefeuille acquéreurs** et appeler les correspondances en priorité.",
      "## Étape 7 — Lancer le suivi vendeur",
      "- Fixer un **plan d'action daté** et un **compte-rendu hebdomadaire** au vendeur (visites, retours, positionnement).",
      "- Programmer un point **prix** à 3 semaines si le nombre de visites est faible.",
      "## Points de vigilance",
      "- Pas de diffusion tant que le **DPE** n'est pas disponible (obligatoire dans l'annonce).",
      "- Toujours faire **signer un bon de visite** aux acquéreurs.",
      "- Mettre à jour le **statut** du dossier dans le CRM à chaque étape.",
    ],
  },
  {
    id: "acquereur",
    titre: "Process acquéreur",
    icone: "🔑",
    resume: "Du premier contact acquéreur jusqu'à la signature.",
    contenu: [
      "Objectif : qualifier, accompagner et convertir un acquéreur en respectant chaque étape.",
      "## Étape 1 — Qualifier (BANT)",
      "- **Budget** : enveloppe réaliste, **apport**, mensualité cible.",
      "- **Financement** : accord de principe bancaire ? courtier ? **finançable** avant de faire visiter.",
      "- **Besoin** : critères (secteur, surface, pièces, extérieur), motivations (SONCAS).",
      "- **Timing** : délai du projet, urgence, bien à vendre en parallèle ?",
      "## Étape 2 — Enregistrer l'acquéreur",
      "- Créer la **fiche acquéreur** dans le CRM avec critères et budget.",
      "- Activer les **alertes / matching** avec le stock et les nouvelles rentrées.",
      "## Étape 3 — Sélectionner et proposer",
      "- Sélectionner **2 à 4 biens** réellement adaptés (ne pas noyer).",
      "- Proposer en priorité les biens **pas encore diffusés** (exclusivités, rentrées récentes).",
      "## Étape 4 — Organiser les visites",
      "- Préparer la visite (points forts, réponses aux objections, infos charges/DPE).",
      "- Faire **signer le bon de visite** à chaque visite.",
      "## Étape 5 — Débrief & relance",
      "- **Débriefer** à chaud : ressenti, points bloquants, niveau d'intérêt.",
      "- **Relancer** selon un rythme (J+1, J+3) ; requalifier si besoin.",
      "## Étape 6 — Offre d'achat",
      "- Rédiger l'**offre** (prix, conditions, financement, délai de validité).",
      "- **Transmettre toute offre écrite** au vendeur (obligation), même basse.",
      "> Aucun versement d'argent n'est exigible au stade de l'offre (art. 1589-1 du Code civil).",
      "## Étape 7 — Négociation & compromis",
      "- Négocier dans l'intérêt des deux parties ; viser un accord qui tient jusqu'à l'acte.",
      "- Déclencher le **compromis** ; vérifier les **conditions suspensives** (prêt, etc.).",
      "## Étape 8 — Suivi jusqu'à l'acte",
      "- Suivre le **délai de rétractation SRU (10 jours)**, le dépôt du dossier de prêt et les conditions suspensives.",
      "- Garder le contact jusqu'à la **signature de l'acte** chez le notaire.",
      "## Points de vigilance",
      "- Ne jamais faire visiter un acquéreur **non qualifié financièrement**.",
      "- Tracer chaque échange dans le **CRM** (statut, prochaine action).",
    ],
  },
  {
    id: "whatsapp",
    titre: "Process groupe WhatsApp",
    icone: "🎥",
    resume: "Diffuser les vidéos de présentation des biens (chasse, mandats, estimations à tester).",
    contenu: [
      "Objectif : le groupe WhatsApp sert à **poster les vidéos de présentation des biens** pour que toute l'équipe les relaie à ses acquéreurs et fasse du matching rapide.",
      "## Quels biens on poste en vidéo",
      "- **Biens en chasse** : repérages intéressants à faire circuler et à tester auprès des acquéreurs.",
      "- **Biens sous mandat** : dès la rentrée, pour une diffusion interne avant/avec la diffusion publique.",
      "- **Estimations « test marché »** : vendeur qui veut tester le marché — **uniquement avec son accord** pour la mise en avant vidéo.",
      "## Réaliser une bonne vidéo",
      "- **Format vertical** (plein écran mobile), **courte** (30 à 90 s), **lumière** et **stabilité** soignées.",
      "- Montrer les **points forts** : entrée, pièces de vie, extérieurs (balcon, terrasse, jardin, vue), atouts du quartier.",
      "- Commentaire dynamique : on **vend l'émotion**, pas seulement les mètres carrés.",
      "- **Pas d'adresse exacte** visible, **pas de données personnelles** du vendeur à l'image.",
      "## Message qui accompagne la vidéo",
      "- **Origine** : 🏹 Chasse · 📝 Mandat · 🧪 Estimation (test marché).",
      "- **Type de bien** + **secteur** (ex. T3 68 m², Jonquières).",
      "- **Prix** (FAI) ou « à définir » si estimation test.",
      "- **Points forts** en 2-3 mots-clés.",
      "- **Négociateur** à contacter (prénom) pour les acquéreurs intéressés.",
      "## Ce que chacun en fait",
      "- **Relayer** la vidéo à ses **acquéreurs en portefeuille** qui correspondent.",
      "- Prévenir **en privé** le négociateur du bien dès qu'un acquéreur est intéressé (ne pas négocier à sa place).",
      "- Mettre à jour le groupe : **sous offre**, **vendu**, **retiré**.",
      "## Règles d'usage",
      "- **Qualité avant quantité** : une vidéo soignée = l'image de l'agence. On évite les vidéos bâclées.",
      "- **Horaires** raisonnables, **pas de spam**, pas de hors-sujet.",
      "- Le groupe est **interne** : les vidéos ne doivent pas être rediffusées à l'extérieur sans accord.",
      "## Points de vigilance",
      "> **Accord du vendeur obligatoire** avant de filmer et de diffuser son bien (droit à l'image du bien, RGPD).",
      "- **Retirer la vidéo** du suivi dès que le bien est **vendu ou retiré**.",
      "- Un **référent** (manager) modère et garde le fil lisible.",
    ],
  },
  {
    id: "leads",
    titre: "Process des leads",
    icone: "📥",
    resume: "Réception, attribution, rappel rapide et suivi des leads entrants.",
    contenu: [
      "Objectif : ne perdre aucun lead et maximiser le taux de transformation par la réactivité.",
      "## Étape 1 — Réception",
      "- Sources : **site agence**, **portails**, **appels entrants**, **réseaux sociaux**, estimation en ligne.",
      "- Chaque lead est **enregistré** immédiatement (CRM / Leads entrant).",
      "## Étape 2 — Attribution",
      "- Attribuer le lead à un **négociateur** selon le secteur / la charge.",
      "- Objectif : **prise en charge rapide** (idéalement sous **5 minutes**, au plus tard dans l'heure).",
      "> La réactivité est décisive : le premier à rappeler sérieusement gagne le plus souvent le contact.",
      "## Étape 3 — Premier contact",
      "- **Rappeler** (téléphone prioritaire sur l'e-mail). Si répondeur : message + SMS + nouvel essai.",
      "- Se présenter, remercier pour la demande, **qualifier** (vendeur / acquéreur, projet, délai).",
      "## Étape 4 — Qualifier & saisir",
      "- Vendeur → orienter vers **RDV estimation**. Acquéreur → **qualifier le financement** puis visites.",
      "- Mettre à jour le **statut** du lead (Nouveau, Traité, RDV fixé, Converti, Perdu) et noter le suivi.",
      "## Étape 5 — Relances programmées",
      "- Si pas joignable / pas mûr : programmer des **relances** (J+1, J+3, J+7, puis mensuel).",
      "- Chaque relance est **tracée** avec la prochaine action.",
      "## Étape 6 — Conversion",
      "- Transformer en **RDV d'estimation** (vendeur) ou **visite** (acquéreur).",
      "- Basculer le dossier dans le pipeline correspondant.",
      "## Étape 7 — Pilotage",
      "- Suivre le **taux de transformation** par source et par négociateur (Suivi des négociateurs).",
      "- Identifier les sources les plus rentables.",
      "## Points de vigilance",
      "- Un lead **non rappelé le jour même** est un lead presque perdu.",
      "- Toujours renseigner le **statut** : un lead sans suivi n'existe pas.",
    ],
  },
  {
    id: "phoning",
    titre: "Process phoning",
    icone: "📞",
    resume: "Organiser et réussir ses sessions d'appels (pige, relances, acquéreurs).",
    contenu: [
      "Objectif : transformer le temps d'appel en rendez-vous, avec méthode et régularité.",
      "## Étape 1 — Préparer la session",
      "- **Bloquer un créneau** fixe dans l'agenda (ex. 9 h-11 h) — non négociable.",
      "- Préparer la **liste cible** (estimations archivées, mandats échus, acquéreurs, PAP…) dans l'outil **Phoning**.",
      "- Choisir le **script** adapté à la cible et fixer un **objectif chiffré** (ex. 20 appels, 2 RDV).",
      "## Étape 2 — Se mettre en condition",
      "- Au calme, **debout** si possible, **sourire** dans la voix.",
      "- Eau à portée, notifications coupées : **100 % concentré** sur l'appel.",
      "## Étape 3 — Dérouler l'appel",
      "- **Accroche** (se présenter, demander 30 s), **découverte** (faire parler), **proposition de valeur**, **closing** (proposer un RDV en alternative).",
      "- S'appuyer sur le **script** de la cible (Centre de formation / outil Phoning).",
      "## Étape 4 — Pointer en direct",
      "- Renseigner le **résultat** de chaque appel dans le tableau Phoning (RDV, rappel, non, non décroché…).",
      "- Noter la **prochaine action** et la date de **rappel**.",
      "## Étape 5 — Gérer les refus",
      "- Un **non** n'est pas un échec : on note, on remercie, on passe au suivant.",
      "- S'appuyer sur la **remotivation** (messages du manager) après une série de refus.",
      "## Étape 6 — Relancer",
      "- Honorer les **rappels datés** : un rappel promis est un rappel tenu.",
      "## Étape 7 — Faire le bilan",
      "- En fin de session : **nombre d'appels**, **RDV décrochés**, **taux de transformation**.",
      "- Ajuster l'approche pour la prochaine session.",
      "## Points de vigilance",
      "- Respecter le **cadre légal du démarchage** (horaires, opt-in) — voir module Cadre légal.",
      "- La **régularité** prime : mieux vaut 1 h tous les jours qu'une journée entière une fois par mois.",
    ],
  },
];
